# Generated by Django 3.1.4 on 2021-10-18 15:28

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0003_auto_20210601_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='note-files'),
        ),
    ]
