# Generated by Django 3.1.4 on 2021-10-19 06:37

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0004_auto_20211018_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='meronotes'),
        ),
    ]
